### PR TITLE
Missing include fix

### LINKED ISSUE #756: Flameshot fails to build with qt 5.15.0
**Flameshot version**
0.6.0

**Describe the bug**
When building flameshot:
```
src/third-party/Qt-Color-Widgets/src/color_wheel.cpp: In member function ‘virtual void color_widgets::ColorWheel::paintEvent(QPaintEvent*)’:
src/third-party/Qt-Color-Widgets/src/color_wheel.cpp:350:22: error: aggregate ‘QPainterPath clip’ has incomplete type and cannot be defined
  350 |         QPainterPath clip;
      |                      ^~~~
src/tools/arrow/arrowtool.cpp:27:68: error: return type ‘class QPainterPath’ is incomplete
   27 | QPainterPath getArrowHead(QPoint p1, QPoint p2, const int thickness) {
      |                                                                    ^
src/tools/arrow/arrowtool.cpp: In function ‘void {anonymous}::getArrowHead(QPoint, QPoint, int)’:
src/tools/arrow/arrowtool.cpp:50:18: error: aggregate ‘QPainterPath path’ has incomplete type and cannot be defined
   50 |     QPainterPath path;
      |                  ^~~~
src/tools/arrow/arrowtool.cpp: In member function ‘virtual void ArrowTool::process(QPainter&, const QPixmap&, bool)’:
src/tools/arrow/arrowtool.cpp:101:97: error: invalid use of void expression
  101 |     painter.fillPath(getArrowHead(m_points.first, m_points.second, m_thickness), QBrush(m_color));
      |                                                                                                 ^
make: *** [Makefile:1477: color_wheel.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:1649: arrowtool.o] Error 1
```

**To Reproduce**
Install Qt 5.15.0
Try building flameshot

**Expected behavior**
Flameshot builds successfully

**System Information**
Linux-5.6.14-gentoo-gf090c5b-dirty-x86_64-AMD_Ryzen_9_3950X_16-Core_Processor-with-gentoo-2.7

Originally reported by @jonasstein in https://bugs.gentoo.org/725930

### PR DESCRIPTION
**Pull request by pavel-the-best**
Closes #756

### CODE REVIEW

**Comment by Ikke** [comment]
The same counts for the bundled Qt-Color-Widgets:

```diff
diff --git a/src/third-party/Qt-Color-Widgets/src/color_wheel.cpp b/src/third-party/Qt-Color-Widgets/src/color_wheel.cpp
index 335b29c..6f4d9fa 100644
--- a/src/third-party/Qt-Color-Widgets/src/color_wheel.cpp
+++ b/src/third-party/Qt-Color-Widgets/src/color_wheel.cpp
@@ -27,6 +27,7 @@
 #include <QLineF>
 #include <QDragEnterEvent>
 #include <QMimeData>
+#include <QPainterPath>
 #include "color_utils.hpp"

 namespace color_widgets {
```

**Comment by pavel-the-best** [comment]
Yes, forgot to include this patch, thanks.
I will update pull request in the next few weeks, because I don't have much time now.

**Comment by borgmanJeremy** [comment]
Fixed through my port.
