### ISSUE TITLE
flameshot indicator icon issue

### ISSUE THREAD

**Issue by dhpowrhost** [flameshot-org/flameshot#92]
I am using both albert launcher and flameshot in ubuntu 16.04. Both have an indicator, however when i installed flameshot the icon of albert changed to the flameshot icon. 

![image](https://user-images.githubusercontent.com/11715805/35036045-61db441c-fb73-11e7-9e95-92c48dd0fdd9.png)

**Comment by ZetaoYang** [comment]
@dhpowrhost Please say how you install flameshot? Please check out the flameshot and albert desktop files.

**Comment by lupoDharkael** [comment]
I don't think it will have anything to do with the desktopfiles.
Does this happen in every session after you reboot?
Check if you can reproduce the issue with 2 different desktops (your usual desktop and other), if it happens only in one it could be a bug in the system.

**Comment by dhpowrhost** [comment]
I installed flameshot using the provided deb file..

**Comment by ZetaoYang** [comment]
@dhpowrhost May be the issue of the system/icon theme or system extensions. I can not reproduce this issue. If you don't mind, I hope you can provide more detailed information about your desktop environment and describe the whole process clearly.

**Comment by ranjitc** [comment]
hi, i've got this problem too. compiled and installed from github.
i'm using ubuntu 16.04 with default unity de.

![image](https://user-images.githubusercontent.com/6581777/35335393-7b308b66-013b-11e8-9246-7871e6d2c254.png)

**Comment by Creteil** [comment]
Hi all,

Same problem occur here between «flameshot » and « mkchromecast » but with some more detailed information's :

- Starting with the 2 apps closed.
- If I run first « flameshot » and then « mkchromecast », the 2 icons render with the « mkchromecast » icon.
- If I run first « mkchromecast » and then « flameshot », the 2 icons render with the « flameshot » icon.

Look like the last application launched force the use of his own icon.

Also, closing 1 of the 2 applications, the icon of the remaining application is used.

Hope it help ...

PS : added a video with the behavior : [flameshot & mkchromecast icon bug](http://bigbob.fun.free.fr/flameshot/flameshot%20and%20mkchromecast%20icon%20bug-2018-02-12_00.52.20.webm)

**Comment by ZetaoYang** [comment]
@Creteil  the video link is unavailable. Can you upload the video to [drop.me](https://drop.me) again?

**Comment by Creteil** [comment]
ZetaoYang

Sorry, but I am out for the moment.
What do you mean by « the video link its unavailable » ???
I am playing it properly from my smartphone without any restrictions...
Do you have any restrictions to access video located in France 🇫🇷 ???

**Comment by ZetaoYang** [comment]
@Creteil  I got it via http proxy.

**Comment by ZetaoYang** [comment]
@Creteil How do you install flameshot? Is it manually compiled and installed?

**Comment by Creteil** [comment]
@ZetaoYang yes, I have build packages by myself (running Ubuntu 15.10 wily).

**Comment by ZetaoYang** [comment]
@Creteil  You compile the source code is downloaded from Github Release [v0.5.0](https://github.com/lupoDharkael/flameshot/archive/v0.5.0.tar.gz)? Or the latest master branch？

**Comment by Creteil** [comment]
bigbob@bigbob-UX31A:~/tmp/Building/flameshot/flameshot$ git --git-dir .git --work-tree . describe --always --tags
v0.5.0-114-gdb8a483

**Comment by ZetaoYang** [comment]
@Creteil Sorry, whether compiled  and installed source code or installed deb directly, I can not reproduce this problem on ubuntu16.04.

**Comment by ranjitc** [comment]
hi @ZetaoYang was wondering if you have tried this with these two particular sw alftred / mkchromecast? if yes, then i guess there is something else on our systems causing this, if not, then maybe these particular sw cause a conflict? or have a common dependency?/

@Creteil sorry to digress from the topic but is the icon in your tray of airdroid? have you managed to get it to work under wine?

**Comment by Creteil** [comment]
@ranjitc what do you mean by « is the icon in your tray of airdroid? » what icon ?

**Comment by Creteil** [comment]
@ZetaoYang what if you close « albert launcher » & « flameshot » then start « flameshot » & « albert launcher » in this order...

**Comment by ranjitc** [comment]
@Creteil this icon ... 
![screen shot 2018-02-12 at 15 04 53](https://user-images.githubusercontent.com/6581777/36090358-1fd6896c-1006-11e8-860d-e4a9bda374b8.png)

**Comment by Creteil** [comment]
@ranjitc look like this icon come from ZetaoYang screenshot, not mine...

**Comment by ZetaoYang** [comment]
@ranjitc I will try in other system.

**Comment by ZetaoYang** [comment]
@ranjitc @Creteil   Linux Mint 18.3 
![image](https://user-images.githubusercontent.com/10769951/36090940-13ca2e3c-101d-11e8-9b32-8abd866dc342.png)

This should be the Ubuntu platform problem. Accurately speaking, it should be a Unity desktop problem

**Comment by Creteil** [comment]
@ZetaoYang ok, thanks, I'm trying to find why and fix ...

**Comment by Creteil** [comment]
@ZetaoYang really strange...

The unity launcher work properly and show right icon per application when opening apps :

![image](https://user-images.githubusercontent.com/27310214/36091180-31477bac-0fe3-11e8-9fe3-252e7e74649a.png)

But the indicator icons in the indicator area at top of the screen show duplicate icon of the last opened app :
![image](https://user-images.githubusercontent.com/27310214/36091297-987a333c-0fe3-11e8-83fd-575decfeabca.png)

**Comment by ZetaoYang** [comment]
@Creteil @ranjitc  
Ubuntu 17.10   **Gnome**
![image](https://user-images.githubusercontent.com/10769951/36131807-b58e3416-10ae-11e8-8469-415e676c70bb.png)

What is certain now is **Unity** desktop problems.

**Comment by ranjitc** [comment]
@ZetaoYang thanks for looking into it !

**Comment by ZetaoYang** [comment]
@ranjitc @Creteil For Ubuntu 16.04 users, try to upgrade to Unity 7.4.5 to see if this issue is resolved.
[changlog](http://changelogs.ubuntu.com/changelogs/pool/main/u/unity/unity_7.4.5+16.04.20171201.3/changelog)

**Comment by Creteil** [comment]
@ZetaoYang I am currently trying to backport unity of xenial on my heavily updated wily release...

At lest I can « give it a try !!! »

**Comment by Creteil** [comment]
@ZetaoYang Do you have an idea of why my compilation of unity bail out with this error ??? :

**`<bigbob@bigbob-UX31A:~/tmp/Building/unity/unity-7.4.0+16.04.20160415$ LANG=C cd /home/bigbob/tmp/Building/unity/unity-7.4.0+16.04.20160415/obj-x86_64-linux-gnu/unity-shared && /usr/bin/x86_64-linux-gnu-g++   -DUSE_X11 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -DGNOME_DESKTOP_USE_UNSTABLE_API -std=c++11 -fno-permissive -Werror -Wall -Wcast-align -Wempty-body -Wformat-security -Winit-self -Warray-bounds -Wno-error=unused-local-typedefs -pthread -DGLEW_MX -pthread -I/usr/include/unity/unity -I/usr/include/libappstream-glib -I/usr/include/libdbusmenu-glib-0.4 -I/usr/include/dee-1.0 -I/usr/include/libindicator3-0.4 -I/usr/include/json-glib-1.0 -I/usr/include/libbamf3 -I/usr/lib/x86_64-linux-gnu/libbamf3/include -I/usr/include/gnome-desktop-3.0 -I/usr/include/Nux-4.0 -I/usr/include/GL -I/usr/include/libdrm -I/usr/include/unity-misc -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/zeitgeist-2.0 -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/startup-notification-1.0 -I/usr/include/compiz -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/startup-notification-1.0 -I/usr/include/gsettings-desktop-schemas -pthread -DGLEW_MX -pthread -fPIC -I/home/bigbob/tmp/Building/unity/unity-7.4.0+16.04.20160415/unity-shared/.. -I/home/bigbob/tmp/Building/unity/unity-7.4.0+16.04.20160415/unity-shared/../services -I/home/bigbob/tmp/Building/unity/unity-7.4.0+16.04.20160415/unity-shared/../UnityCore -I/home/bigbob/tmp/Building/unity/unity-7.4.0+16.04.20160415/unity-shared/../plugins/unityshell/src -I/home/bigbob/tmp/Building/unity/unity-7.4.0+16.04.20160415/obj-x86_64-linux-gnu -I/home/bigbob/tmp/Building/unity/unity-7.4.0+16.04.20160415/obj-x86_64-linux-gnu/unity-shared     -include unity-shared_pch.hh  -fpch-preprocess  -Winvalid-pch  -o CMakeFiles/unity-shared.dir/AppStreamApplication.cpp.o -c /home/bigbob/tmp/Building/unity/unity-7.4.0+16.04.20160415/unity-shared/AppStreamApplication.cpp
In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/Nux-4.0/NuxCore/SystemGNU.h:37,
                 from /usr/include/Nux-4.0/NuxCore/NuxCore.h:125,
                 from /usr/include/Nux-4.0/Nux/Nux.h:26,
                 from /home/bigbob/tmp/Building/unity/unity-7.4.0+16.04.20160415/unity-shared/pch/unity-shared_pch.hh:30:
/usr/include/glib-2.0/glib/gmacros.h:260:24: error: expected declaration before ‘}’ token
 #define G_END_DECLS    }
                        ^
/usr/include/libappstream-glib/as-tag.h:156:1: note: in expansion of macro ‘G_END_DECLS’
 G_END_DECLS
 ^
bigbob@bigbob-UX31A:~/tmp/Building/unity/unity-7.4.0+16.04.20160415/obj-x86_64-linux-gnu/unity-shared$>`**

It's hours I am searching how to fix this compilation error without any success (it look like my understanding of this error is limited).

**Comment by ZetaoYang** [comment]
@Creteil Why do you compile and install from source?

**Comment by Creteil** [comment]
@ZetaoYang Because I can't upgrade my actual wily to 16.04.3 LTS without start from scratch.
By the way, I am tired of compiling this stuff, so, I am in the process to install the 16.04.3 LTS on another computer to see if every applications and GUI stuff work like I expect and then migrate my principal laptop to 16.04.3 LTS after check tests completed successfully ...

**Comment by ranjitc** [comment]
@ZetaoYang no luck :( problem persists on 7.4.5 ... oh well 18.04 is around the corner

**Comment by ZetaoYang** [comment]
@ranjitc @Creteil You can try AppImage, it works well on Ubuntu14.04 when I installed indicator-systemtray-unity.

**Comment by ranjitc** [comment]
@ZetaoYang thanks, will give it a shot

**Comment by Creteil** [comment]
@ZetaoYang F***k !!! On a fresh installed 16.04 LTS exactly same problem...

**Comment by ZetaoYang** [comment]
@ranjitc @Creteil 
I have a compromise solution：
1. For Ubuntu 14.04/16.04, install `indicator-systemtray-unity`  (**Only Unity** desktop environment)
Ubuntu 14.04 support is the best, but Ubuntu 16.04, still can be used.
```
sudo apt-add-repository ppa:fixnix/indicator-systemtray-unity  
sudo apt-get update
sudo apt-get install indicator-systemtray-unity
```
Once installed, log out and log in and Indicator Systemtray Unity should start automatically.
##### Settings
To change the mode position: press the middle mouse button on the indicator. 
The horizontal position can be changed: scrolling the mouse over the indicator.

Settings can be changed in gsettings:/net/launchpad/indicator/systemtray (use **dconf-editor**).
##### install dconf-editor
`sudo apt-get install dconf-editor`

2. **Be sure to use  AppImage for flameshot**
AppImage: https://drop.me/o293yD
latest AppImage build can be found in https://travis-ci.org/lupoDharkael/flameshot/jobs/343078928
NOTE! support left-click the flameshot icon to take a screenshot.

Ubuntu16.04 Unity:
![](https://user-images.githubusercontent.com/10769951/36368498-7f5d82aa-1592-11e8-8488-348ab71f6420.png)

Gif:
![](https://user-images.githubusercontent.com/10769951/36370661-7a673126-159a-11e8-8627-39ee6c84b8cc.gif)

**Comment by ZetaoYang** [comment]
@ranjitc 
![image](https://user-images.githubusercontent.com/10769951/36373624-a4e24220-15a3-11e8-86bb-fd6a0f6443a8.png)


![image](https://user-images.githubusercontent.com/10769951/36373478-3ce95b2c-15a3-11e8-879a-3473d32c1bc5.png)

![image](https://user-images.githubusercontent.com/10769951/36373551-76de8762-15a3-11e8-9f99-f6ed2c4f9155.png)

**Comment by ranjitc** [comment]
thanks! i had made it to the xenial link, didnt think of looking in the logs 🤦‍♂️

**Comment by Creteil** [comment]
Hi all,

I have migrated to Ubuntu 17.10 + Unity, everything is working fine now, except the autostart of flameshot :-(

![image](https://user-images.githubusercontent.com/27310214/36497263-17830a6a-173b-11e8-897d-72ca714f5787.png)
![image](https://user-images.githubusercontent.com/27310214/36497308-3e7668ce-173b-11e8-85e7-0326222575c0.png)

**Comment by ZetaoYang** [comment]
@Creteil Could you try [albert](https://github.com/albertlauncher/albert)？

**Comment by ranjitc** [comment]
@Creteil i think @ZetaoYang meant only to check if the icon problem is solved with albert in 17.10 as the original request was for albert

**Comment by Creteil** [comment]
@ranjitc I can check for sure, but there is no debian source package and I don't want to install it from scratch.

**Comment by ranjitc** [comment]
@Creteil ah ok thanks

**Comment by ZetaoYang** [comment]
albert PPA:
https://launchpad.net/~flexiondotorg/+archive/ubuntu/albert

**Comment by Creteil** [comment]
@ZetaoYang installed from : http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/a/albert/

Look good, have a look :

![image](https://user-images.githubusercontent.com/27310214/36548655-2760a120-17f1-11e8-9a9f-1f287631fcfa.png)

**Comment by ZetaoYang** [comment]
@Creteil Thank you very much.

**Comment by ZetaoYang** [comment]
@lupoDharkael An old programmer, he read the flameshot source, told me that 
> flameshot is to use `QDBusInterface` and the system `org.freedesktop.Notifications` service to interact, ID specified as 0. Should be assigned a value of 0 ID generated by the system random ID, perhaps the algorithm is some kind of hash, and flameshot and albert's calculations just hit.

**Comment by pyhoff** [comment]
Morning, looking for color invert feature button. Is this even possible right now with flameshot.
